# -*- coding: utf-8 -*-
{
    'name': "SAP Integration",
    'summary': """SAP Integration""",
    'description': """SAP Integration""",
    'author': "Moogah",
    'website': "http://www.Moogah.com",
    'category': 'Uncategorized',
    'version': '13.0.1.9.2',
    'depends': [
        'account',
        'product',
        'uom',
        'sales_blanket_order',
        'sale',
        'delivery',
        'eq_stock_move_cancel',
        'stock_move_line_auto_fill',
        'website_sale',
    ],
    'data': [
        'views/templates.xml',
        'views/view_sap_sinc_errors.xml',
        'views/view_sap_stock.xml',
        'views/sap_ws_credentials.xml',
        'views/view_sap_brsch.xml',
        'views/view_sap_waers.xml',
        'views/view_sap_invoice_position.xml',
        'views/view_sap_invoice_interlocutor.xml',
        'views/view_sap_invoice.xml',
        'views/view_sap_werk.xml',
        'views/view_sap_vbak_auart.xml',
        'views/view_sap_delivery_position.xml',
        'views/view_sap_delivery_interlocutor.xml',
        'views/view_sap_delivery.xml',
        'views/std_views.xml',
        'views/view_kschl.xml',
        'views/view_sap_sales.xml',
        'views/view_sap_material.xml',
        'views/view_sap_sales_interlocutor.xml',
        'views/view_sap_sales_position.xml',
        'views/view_sap_knvv.xml',
        'views/view_sap_knvp.xml',
        'views/view_sap_knb1.xml',
        'views/view_sap_kna1.xml',
        'views/view_sap_vbak_vtweg.xml',
        'views/view_sap_vbak_spart.xml',
        'views/view_sap_vbak_vkorg.xml',
        'views/view_sap_rej_reason.xml',
        'views/view_sap_lfa1.xml',
        'views/view.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'application': True,
}
